package upsdemos.domainmodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Employee Type")
   private java.lang.String employeeType;
   @org.kie.api.definition.type.Label(value = "Hourly Pay")
   private double hourlyPay;
   @org.kie.api.definition.type.Label(value = "Home Building")
   private java.lang.String homeBuilding;
   @org.kie.api.definition.type.Label(value = "Home Op Type")
   private java.lang.String homeOpType;
   @org.kie.api.definition.type.Label(value = "Home Center")
   private java.lang.String homeCenter;

   public Employee()
   {
   }

   public java.lang.String getEmployeeType()
   {
      return this.employeeType;
   }

   public void setEmployeeType(java.lang.String employeeType)
   {
      this.employeeType = employeeType;
   }

   public double getHourlyPay()
   {
      return this.hourlyPay;
   }

   public void setHourlyPay(double hourlyPay)
   {
      this.hourlyPay = hourlyPay;
   }

   public java.lang.String getHomeBuilding()
   {
      return this.homeBuilding;
   }

   public void setHomeBuilding(java.lang.String homeBuilding)
   {
      this.homeBuilding = homeBuilding;
   }

   public java.lang.String getHomeOpType()
   {
      return this.homeOpType;
   }

   public void setHomeOpType(java.lang.String homeOpType)
   {
      this.homeOpType = homeOpType;
   }

   public java.lang.String getHomeCenter()
   {
      return this.homeCenter;
   }

   public void setHomeCenter(java.lang.String homeCenter)
   {
      this.homeCenter = homeCenter;
   }

   public Employee(java.lang.String employeeType, double hourlyPay,
         java.lang.String homeBuilding, java.lang.String homeOpType,
         java.lang.String homeCenter)
   {
      this.employeeType = employeeType;
      this.hourlyPay = hourlyPay;
      this.homeBuilding = homeBuilding;
      this.homeOpType = homeOpType;
      this.homeCenter = homeCenter;
   }

}