package upsdemos.domainmodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmployeeEligibility implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Is Eligible")
   private java.lang.Boolean eligible;
   @org.kie.api.definition.type.Label(value = "Employee Id")
   private java.lang.Long empId;

   public EmployeeEligibility()
   {
   }

   public java.lang.Boolean getEligible()
   {
      return this.eligible;
   }

   public void setEligible(java.lang.Boolean eligible)
   {
      this.eligible = eligible;
   }

   public java.lang.Long getEmpId()
   {
      return this.empId;
   }

   public void setEmpId(java.lang.Long empId)
   {
      this.empId = empId;
   }

   public EmployeeEligibility(java.lang.Boolean eligible, java.lang.Long empId)
   {
      this.eligible = eligible;
      this.empId = empId;
   }

}