package upsdemos.domainmodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Employee Type")
   private java.lang.String employeeType;
   @org.kie.api.definition.type.Label("Hourly Pay")
   private double hourlyPay;
   @org.kie.api.definition.type.Label("Home Building")
   private java.lang.String homeBuilding;
   @org.kie.api.definition.type.Label("Home Op Type")
   private java.lang.String homeOpType;
   @org.kie.api.definition.type.Label("Home Center")
   private java.lang.String homeCenter;

   @org.kie.api.definition.type.Label("Employee Id")
   private java.lang.Long empId;

   @org.kie.api.definition.type.Label(value = "Facility")
   private upsdemos.domainmodel.Facility facility;

   public Employee()
   {
   }

   public java.lang.String getEmployeeType()
   {
      return this.employeeType;
   }

   public void setEmployeeType(java.lang.String employeeType)
   {
      this.employeeType = employeeType;
   }

   public double getHourlyPay()
   {
      return this.hourlyPay;
   }

   public void setHourlyPay(double hourlyPay)
   {
      this.hourlyPay = hourlyPay;
   }

   public java.lang.String getHomeBuilding()
   {
      return this.homeBuilding;
   }

   public void setHomeBuilding(java.lang.String homeBuilding)
   {
      this.homeBuilding = homeBuilding;
   }

   public java.lang.String getHomeOpType()
   {
      return this.homeOpType;
   }

   public void setHomeOpType(java.lang.String homeOpType)
   {
      this.homeOpType = homeOpType;
   }

   public java.lang.String getHomeCenter()
   {
      return this.homeCenter;
   }

   public void setHomeCenter(java.lang.String homeCenter)
   {
      this.homeCenter = homeCenter;
   }

   public java.lang.Long getEmpId()
   {
      return this.empId;
   }

   public void setEmpId(java.lang.Long empId)
   {
      this.empId = empId;
   }

   public upsdemos.domainmodel.Facility getFacility()
   {
      return this.facility;
   }

   public void setFacility(upsdemos.domainmodel.Facility facility)
   {
      this.facility = facility;
   }

   public Employee(java.lang.String employeeType, double hourlyPay,
         java.lang.String homeBuilding, java.lang.String homeOpType,
         java.lang.String homeCenter, java.lang.Long empId,
         upsdemos.domainmodel.Facility facility)
   {
      this.employeeType = employeeType;
      this.hourlyPay = hourlyPay;
      this.homeBuilding = homeBuilding;
      this.homeOpType = homeOpType;
      this.homeCenter = homeCenter;
      this.empId = empId;
      this.facility = facility;
   }

}