package upsdemos.domainmodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmployeeEligibility implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Is Eligible")
   private java.lang.Boolean eligible;
  

   public EmployeeEligibility()
   {
   }

   public java.lang.Boolean getEligible()
   {
      return this.eligible;
   }

   public void setEligible(java.lang.Boolean eligible)
   {
      this.eligible = eligible;
   }

   
   public EmployeeEligibility(java.lang.Boolean eligible)
   {
      this.eligible = eligible;
      
   }

}