package upsdemos.domainmodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmployeeEligibility implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public EmployeeEligibility() {
    }

}