package upsdemos.domainmodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Facility implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Building Mnemonic")
   private java.lang.String buildingMnemonicCode;
   @org.kie.api.definition.type.Label(value = "State")
   private java.lang.String state;
   @org.kie.api.definition.type.Label(value = "City")
   private java.lang.String city;
   @org.kie.api.definition.type.Label(value = "Zip")
   private java.lang.String zip;

   public Facility()
   {
   }

   public java.lang.String getBuildingMnemonicCode()
   {
      return this.buildingMnemonicCode;
   }

   public void setBuildingMnemonicCode(java.lang.String buildingMnemonicCode)
   {
      this.buildingMnemonicCode = buildingMnemonicCode;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getZip()
   {
      return this.zip;
   }

   public void setZip(java.lang.String zip)
   {
      this.zip = zip;
   }

   public Facility(java.lang.String buildingMnemonicCode,
         java.lang.String state, java.lang.String city, java.lang.String zip)
   {
      this.buildingMnemonicCode = buildingMnemonicCode;
      this.state = state;
      this.city = city;
      this.zip = zip;
   }

}